sudo: required

services:
  - docker

env:
  - COMPOSE_FILE=docker-compose.yml

before_script:
  - docker build -t andygrunwald/fom-latex-template .

script:
  - docker-compose up --exit-code-from fom
  - docker-compose run --service-ports fom ./compile.sh "en"
